<?php

// amazon keys
$awsApiKey = "";        // Specify key here
$awsApiSecretKey = "";  // Specify secret key here

// amazon s3 storage settings
$awsS3Bucket = "fb2pdf";

// amazon Simple Queue Service settings
$awsSQSQueue = "fb2pdf";
$awsSQSTimeout = 600;

// secret phrase
$secret = "";   // Specify secret phrase here

// db settings
$dbServer = "localhost";     // Specify DB server here
$dbName = "FB2PDF";       // Specify DB name here
$dbUser = "fb2pdf";       // Specify DB user here
$dbPassword = "XXX";   // Specify DB password here

// converter version
$convVersion = 3.14;
?>