-- Creates FB2PDF database
-- must be executed as admin user

CREATE DATABASE FB2PDF DEFAULT CHARACTER SET utf8;
GRANT ALL PRIVILEGES ON FB2PDF.* TO fb2pdf@'localhost.localdomain' IDENTIFIED BY 'XXX';
GRANT ALL PRIVILEGES ON FB2PDF.* TO fb2pdf@'localhost' IDENTIFIED BY 'XXX';
GRANT ALL PRIVILEGES ON FB2PDF.* TO fb2pdf@'%' IDENTIFIED BY 'XXX';

GRANT LOCK TABLES ON FB2PDF.* TO fb2pdf@'localhost.localdomain' IDENTIFIED BY 'XXX';
GRANT LOCK TABLES ON FB2PDF.* TO fb2pdf@'localhost' IDENTIFIED BY 'XXX';
GRANT LOCK TABLES ON FB2PDF.* TO fb2pdf@'%' IDENTIFIED BY 'XXX';

