#!/usr/bin/env python2.4

'''
Simple Tool to send messages to the queue

Author: Vadim Zaliva <lord@crocodile.org>
'''

import getopt,sys,string,time

from ConfigParser import ConfigParser

from boto.sqs import Connection
from boto.sqs.message import Message
from boto.exception import SQSError

# --- Code ---

def usage():
    sys.stderr.write("Usage: queue_send.py [-v] -c cfgfile -f file\n")

def main():
      cfgfile = None
      ifile = None
      verbose = False
      
      try:
            opts, args = getopt.getopt(sys.argv[1:], "vc:f:", ["verbose", "cfgfile", "file"])
      except getopt.GetoptError:
            usage()
            sys.exit(2)
      for o, a in opts:
            if o in ("-c", "--cfgfile"):
                  cfgfile = a
            if o in ("-f", "--file"):
                  ifile = a
            if o in ("-v", "--verbose"):
                  verbose = True

      if len(args) != 0 or cfgfile is None or ifile is None:
            usage()
            sys.exit(2)

      f=open(ifile)
      msgtext=f.read()
      f.close()

      cfg = ConfigParser()
      cfg.read(cfgfile)

      c = Connection(aws_access_key_id=cfg.get('aws','public'), aws_secret_access_key=cfg.get('aws','private'))
      
      qname = cfg.get('queue','name')
      q = c.create_queue(qname)
      m = Message()
      m.set_body(msgtext)
      rs = q.write(m)
      print "Message sent"

if __name__ == "__main__":
    main()

